spring:
  datasource:
    url: jdbc:mysql://node01:3306/txkt?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false
    username: root
    password: @WSX3edc
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      jdbc:
        time_zone: GMT+8
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: false
        event:
          merge:
            entity_copy_observer: allow

server:
  #  port: 8080
  port: 8901


