SELECT video_type1,         
       video_type2,         
       video_type3,         
       video_title,         
       video_url,           
       video_sections_num,  
       video_index_page,    
       organ_name,          
       price,               
       person_num,          
       recently_study_num,  
       sign_up_num,         
       video_praise_degree, 
       organ_praise_degree, 
       organ_video_num,     
       organ_all_person_num,
       grab_time,           
       FROM_UNIXTIME(CAST(NOW() AS BIGINT), 'yyyy-MM-dd HH:mm:ss') AS elt_time,
       DATE_FORMAT(TO_TIMESTAMP(grab_time, 'yyyy-MM-dd HH:mm:ss'), 'yyyy-MM-dd') AS dt 
  FROM mysql_tencent_study_video_spider         